package dto

import (
	"fmt"
	"github.com/paulrozhkin/sport-tracker/internal/models"
	"strings"
	"time"
)

// ProblemDetails https://www.rfc-editor.org/rfc/rfc7807
type ProblemDetails struct {
	// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced,
	// it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]).
	// When this member is not present, its value is assumed to be "about:blank".
	Type string `json:"type,omitempty"`

	// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem,
	// except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).
	Title string `json:"title"`

	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`

	// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance string `json:"instance"`

	// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
	Status int `json:"status"`

	// Invalid params in request
	InvalidParams []*models.ParamError `json:"invalid-params,omitempty"`
}

// JsonDate Date in ISO 8601 format
type JsonDate struct {
	time.Time
}

const layout = time.RFC3339

func (c *JsonDate) UnmarshalJSON(b []byte) (err error) {
	s := strings.Trim(string(b), `"`) // remove quotes
	if s == "null" {
		return
	}
	c.Time, err = time.Parse(layout, s)
	if err != nil {
		return err
	}
	return
}

func (c JsonDate) MarshalJSON() ([]byte, error) {
	if c.Time.IsZero() {
		return nil, nil
	}
	return []byte(fmt.Sprintf(`"%s"`, c.Time.Format(layout))), nil
}
